name: Go Release

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -o terminal server.go

    - name: Add to Release
      uses: actions/upload-release-asset@v1
      with:
        name: terminal
        path: terminal

    - name: Set Action Secret
      env:
        SECRET_KEY: ${{ secrets.ACCESS_TOKEN  }}
      run: |
        # 这里使用密钥进行相关操作
        echo "The secret key is: $SECRET_KEY"